---
# vim: set ft=ansible:


- name: install docker dependencies
  become: true
  shell: apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
  args:
    warn: no

- name: install docker key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: yes

- name: ensure docker.service.d is created
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: ensure correct docker.conf for systemd is created
  become: true
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
    owner: root
    group: root
    mode: 0644

- name: install docker
  become: true
  apt:
    name: docker-ce
    state: present
  notify: restart docker

- name: add docker group
  become: true
  group:
    name: docker
    state: present

- name: add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: pull images
  become: true
  command: docker pull {{ item | quote }}
  args:
    warn: no
  with_items: "{{ docker_images }}"

- name: clean docker garbage
  become: true
  command: docker system prune -f
  args:
    warn: no
