---
# vim: set ft=ansible:


- name: clone dotfiles
  git:
    accept_hostkey: yes
    dest: ~/.dotfiles
    repo: "{{ dotfiles_link }}"

- name: stow dotfiles
  command: stow -t ~ -R {{ item | quote }}
  args:
    chdir: ~/.dotfiles
  with_items: "{{ stow_dotfiles }}"
