---
# vim: set ft=ansible:


- include: ./apt.yaml
- include: ./ntp.yaml
- include: ./locales.yaml
- include: ./ssh.yaml
- include: ./htop.yaml
- include: ./pip.yaml
- include: ./docker.yaml
- include: ./dotfiles.yaml
- include: ./shell.yaml
- include: ./nodejs.yaml
- include: ./pyenv.yaml
- include: ./neovim.yaml
