---
# vim: set ft=ansible:

- name: remove ntp
  become: true
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoremove: yes
  with_items:
  - ntp
  - ntpdate

- name: set timezone
  become: true
  command: timedatectl set-timezone {{ ntp_timezone | quote }}

- name: set ntp
  become: true
  command: timedatectl set-ntp true

- name: ensure timesyncd.d directory created
  become: true
  file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory

- name: set timesyncd config
  become: true
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf.d/zzz-own-config.conf
    owner: root
    group: root
    mode: 0644
  notify: restart timesyncd
