---
# vim: set ft=ansible:


- name: copy ssh keys from the local machine
  copy:
    src: "~/.ssh/{{ item }}"
    dest: ~/.ssh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0400
  with_items:
  - id_rsa
  - id_rsa.pub
