---
# vim: set ft=ansible:


- hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: install ansible dependencies
    raw: >
      sh -c
      'apt-get update && apt-get install -y --no-install-recommends aptitude python python-apt python3-apt'

  - name: remove puppet labs stuff
    file:
      name: "{{ item }}"
      state: absent
    with_items:
    - /etc/apt/sources.list.d/puppetlabs-pc1.list
    - /etc/apt/trusted.gpg.d/puppetlabs-pc1-keyring.gpg

  - name: remove elastic user
    user:
      name: elastic
      state: absent
      remove: yes


- hosts: all
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    DEBIAN_FRONTEND: noninteractive
  gather_facts: true
  roles:
  - {{ cookiecutter.devbox_role }}
