# -*- mode: ruby -*-
# vi: set ft=ruby :

CURRENT_DIR = File.expand_path(File.dirname(__FILE__))
ANSIBLE_TAGS = ENV.fetch('ANSIBLE_TAGS', 'all')
DISK_SIZE = {{ cookiecutter.disk_size }}

Vagrant.configure('2') do |config|
  config.vm.box_check_update = false
  config.vm.base_address = '{{ cookiecutter.ip }}'
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = '{{ cookiecutter.hostname }}'
  config.vm.synced_folder '.', '/shared', type: 'virtualbox'

  config.ssh.forward_agent = true

  config.vm.provider 'virtualbox' do |vb|
    if Vagrant.has_plugin?('vagrant-disksize')
      config.disksize.size = "#{DISK_SIZE}GB"
    else
      print 'vagrant-disksize is not installed, cannot set correct disksize'
    end

    vb.gui = false
    vb.memory = {{ cookiecutter.memory }}
    vb.cpus = {{ cookiecutter.cpus }}
  end

  if not Vagrant.has_plugin?('vagrant-host-shell')
    print 'Ansible Galaxy roles should be installed.'
    print 'Please run ansible-galaxy install -r ansible-requirements.yaml'
    print 'Or install vagrant-host-shell plugin'
  end

  config.vm.provision :host_shell do |host_shell|
    host_shell.inline = "cd '#{CURRENT_DIR}' && find provision -depth 2 -type d | grep -vE '^provision/roles/{{ cookiecutter.devbox_role }}' | xargs rm -rf && ansible-galaxy install -r '#{CURRENT_DIR}/ansible-requirements.yaml'"
  end

  # config.vm.provision 'ansible' do |ansible|
  #   ansible.playbook = 'provision/site.yaml'
  #   ansible.ask_vault_pass = true
  #   ansible.tags = ANSIBLE_TAGS
  #   ansible.compatibility_mode = '2.0'
  # end
end
